services:
  database:
    image: postgres:14.6-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
  web-app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./project:/project
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
    depends_on:
      - database
  redis:
    image: redis:7.0.5-alpine
    hostname: redis
  worker:
    build: 
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./project:/project
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
  worker2:
    build: 
      context: .
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./project:/project
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
  flower:
    build: 
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./project:/project
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"
    